import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1786815960534 implements MigrationInterface {
    name = 'Baseline1786815960534'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "t_api_key" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "key_hash" varchar(255) NOT NULL, "prefix" varchar(16), "created_at" datetime NOT NULL, "last_used_at" datetime, "scopes" varchar(255) NOT NULL DEFAULT ('read,scan,export'), "target_kind" varchar(20), "target_id" integer, "expires_at" datetime)`);
        await queryRunner.query(`CREATE TABLE "t_agent" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" varchar(500), "kind" varchar(20) NOT NULL, "labels" varchar(255), "credentials_mode" varchar(20) NOT NULL, "enabled" boolean NOT NULL, "max_concurrent" integer, "api_key_id" varchar(36), "hostname" varchar(255), "platform" varchar(255), "version" varchar(50), "scanner_engine" varchar(50), "sealing_public_key" varchar(255), "capabilities" json, "contract_version" varchar(20), "last_seen_at" datetime, "created_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_container" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "registry" varchar(255), "image_name" varchar(255) NOT NULL, "tag" varchar(255) NOT NULL, "required_agent_label" varchar(255), "scan_interval_minutes" integer, "scan_cron" varchar(255), "last_scheduled_scan_at" datetime)`);
        await queryRunner.query(`CREATE TABLE "t_ssh_key" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "private_key" text NOT NULL, "public_key" text, "created_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_repository" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar(255) NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "required_agent_label" varchar(255), "name" varchar(255), "scan_interval_minutes" integer, "scan_cron" varchar(255), "last_scheduled_scan_at" datetime, "ssh_key_id" varchar(36))`);
        await queryRunner.query(`CREATE TABLE "t_scan" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "status" varchar(255) NOT NULL, "required_agent_label" varchar(255), "sbom" json, "cves" json, "summary" json, "duration_ms" bigint, "findings_count" integer NOT NULL DEFAULT (0), "new_issues_count" integer NOT NULL DEFAULT (0), "resolved_issues_count" integer NOT NULL DEFAULT (0), "error" text, "created_at" datetime NOT NULL, "version" varchar(255), "project_type" varchar(255), "repo_id" integer, "container_id" integer, "claimed_by" varchar(64), "claimed_at" datetime, "lease_expires_at" datetime, "attempts" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE INDEX "idx_scan_file" ON "t_scan" ("status", "required_agent_label", "created_at", "id") `);
        await queryRunner.query(`CREATE TABLE "t_ai_review_result" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "model" varchar(255) NOT NULL, "prompt" text NOT NULL, "response" text, "status" varchar(50) NOT NULL, "error" varchar(500), "created_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_audit_log" ("id" varchar PRIMARY KEY NOT NULL, "description" varchar(255) NOT NULL, "operation_type" varchar(255) NOT NULL, "resource_id" varchar(255) NOT NULL, "timestamp" datetime NOT NULL, "user_id" varchar(255), "ip_address" varchar(64), "user_agent" varchar(255), "previous_hash" varchar(64), "entry_hash" varchar(64))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_log_ordre" ON "t_audit_log" ("timestamp", "id") `);
        await queryRunner.query(`CREATE TABLE "t_issue" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "repo_id" integer, "container_id" integer, "fingerprint" varchar(64) NOT NULL, "type" varchar(50) NOT NULL, "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50), "severity" varchar(50), "epss_score" real, "is_kev" boolean NOT NULL DEFAULT (0), "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "description" text, "state" varchar(20) NOT NULL DEFAULT ('open'), "first_seen_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "resolved_at" datetime, "first_seen_scan_id" integer, "last_seen_scan_id" integer, "times_seen" integer NOT NULL DEFAULT (1), "triage_status" varchar(30) NOT NULL DEFAULT ('under_review'), "triage_justification" varchar(64), "triage_comment" text, "triaged_by" varchar(255), "triaged_at" datetime, "triage_expires_at" datetime, "is_direct_dependency" boolean, "line" integer, "ticket_ref" varchar(64), "ticket_url" varchar(500))`);
        await queryRunner.query(`CREATE TABLE "t_finding" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "type" varchar(50) NOT NULL, "severity" varchar(50), "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50) NOT NULL, "epss_score" real, "is_kev" boolean NOT NULL, "created_at" datetime NOT NULL, "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "issue_id" integer, "is_direct_dependency" boolean, "line" integer, "description" text)`);
        await queryRunner.query(`CREATE TABLE "t_gate_policy" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "target_kind" varchar(20) NOT NULL, "target_id" integer NOT NULL, "version" integer NOT NULL, "is_active" boolean, "fail_on_severity" varchar(20), "fail_on_kev" boolean NOT NULL, "fixable_only" boolean NOT NULL, "include_triaged" boolean NOT NULL, "include_ai_review" boolean NOT NULL, "note" text, "created_by" varchar(255), "created_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_leader_lease" ("name" varchar(64) PRIMARY KEY NOT NULL, "holder" varchar(64), "acquired_at" datetime, "expires_at" datetime, "updated_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_login_attempt" ("id" varchar PRIMARY KEY NOT NULL, "counter_key" varchar(255) NOT NULL, "occurred_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_outbox_message" ("id" varchar PRIMARY KEY NOT NULL, "message_type" varchar(50) NOT NULL, "payload" json NOT NULL, "status" varchar(20) NOT NULL, "attempts" integer NOT NULL, "next_attempt_at" datetime, "last_error" text, "created_at" datetime NOT NULL, "sent_at" datetime)`);
        await queryRunner.query(`CREATE TABLE "t_processed_message" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "message_id" varchar(64) NOT NULL, "message_type" varchar(50) NOT NULL, "agent_id" varchar(36), "processed_at" datetime NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "t_user" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "username" varchar(255) NOT NULL, "email" varchar(255), "password" varchar(255), "display_name" varchar(255), "avatar_url" varchar(255), "role" varchar(255) NOT NULL, "is_active" boolean NOT NULL, "github_id" varchar(255), "keycloak_id" varchar(255), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "must_change_password" boolean NOT NULL, CONSTRAINT "UQ_cebdcd668896f79744000f50dd3" UNIQUE ("username"), CONSTRAINT "UQ_1d0b42896fa20240f9ffcc8012a" UNIQUE ("email"), CONSTRAINT "UQ_16391e9a0f1e1b6e286ec6ff9ba" UNIQUE ("github_id"), CONSTRAINT "UQ_43acce0aa9f45484164891a5489" UNIQUE ("keycloak_id"))`);
        await queryRunner.query(`CREATE TABLE "t_session" ("token" varchar(64) PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "created_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "expires_at" datetime NOT NULL, "user_agent" varchar(255), "ip_address" varchar(64))`);
        await queryRunner.query(`CREATE TABLE "t_setting" ("key" varchar(255) PRIMARY KEY NOT NULL, "value" varchar(255))`);
        await queryRunner.query(`CREATE TABLE "temporary_t_agent" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" varchar(500), "kind" varchar(20) NOT NULL, "labels" varchar(255), "credentials_mode" varchar(20) NOT NULL, "enabled" boolean NOT NULL, "max_concurrent" integer, "api_key_id" varchar(36), "hostname" varchar(255), "platform" varchar(255), "version" varchar(50), "scanner_engine" varchar(50), "sealing_public_key" varchar(255), "capabilities" json, "contract_version" varchar(20), "last_seen_at" datetime, "created_at" datetime NOT NULL, CONSTRAINT "FK_28216d89bbec1752bb00c82fb3d" FOREIGN KEY ("api_key_id") REFERENCES "t_api_key" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_agent"("id", "name", "description", "kind", "labels", "credentials_mode", "enabled", "max_concurrent", "api_key_id", "hostname", "platform", "version", "scanner_engine", "sealing_public_key", "capabilities", "contract_version", "last_seen_at", "created_at") SELECT "id", "name", "description", "kind", "labels", "credentials_mode", "enabled", "max_concurrent", "api_key_id", "hostname", "platform", "version", "scanner_engine", "sealing_public_key", "capabilities", "contract_version", "last_seen_at", "created_at" FROM "t_agent"`);
        await queryRunner.query(`DROP TABLE "t_agent"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_agent" RENAME TO "t_agent"`);
        await queryRunner.query(`CREATE TABLE "temporary_t_repository" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar(255) NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "required_agent_label" varchar(255), "name" varchar(255), "scan_interval_minutes" integer, "scan_cron" varchar(255), "last_scheduled_scan_at" datetime, "ssh_key_id" varchar(36), CONSTRAINT "FK_154e4f287a89244dd8e19591fde" FOREIGN KEY ("ssh_key_id") REFERENCES "t_ssh_key" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_repository"("id", "url", "branch", "sub_path", "required_agent_label", "name", "scan_interval_minutes", "scan_cron", "last_scheduled_scan_at", "ssh_key_id") SELECT "id", "url", "branch", "sub_path", "required_agent_label", "name", "scan_interval_minutes", "scan_cron", "last_scheduled_scan_at", "ssh_key_id" FROM "t_repository"`);
        await queryRunner.query(`DROP TABLE "t_repository"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_repository" RENAME TO "t_repository"`);
        await queryRunner.query(`DROP INDEX "idx_scan_file"`);
        await queryRunner.query(`CREATE TABLE "temporary_t_scan" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "status" varchar(255) NOT NULL, "required_agent_label" varchar(255), "sbom" json, "cves" json, "summary" json, "duration_ms" bigint, "findings_count" integer NOT NULL DEFAULT (0), "new_issues_count" integer NOT NULL DEFAULT (0), "resolved_issues_count" integer NOT NULL DEFAULT (0), "error" text, "created_at" datetime NOT NULL, "version" varchar(255), "project_type" varchar(255), "repo_id" integer, "container_id" integer, "claimed_by" varchar(64), "claimed_at" datetime, "lease_expires_at" datetime, "attempts" integer NOT NULL DEFAULT (0), CONSTRAINT "FK_d6f19b8301b5a4aeb38208bc219" FOREIGN KEY ("container_id") REFERENCES "t_container" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a8c35b7077df870971f96c6ec05" FOREIGN KEY ("repo_id") REFERENCES "t_repository" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_scan"("id", "branch", "sub_path", "status", "required_agent_label", "sbom", "cves", "summary", "duration_ms", "findings_count", "new_issues_count", "resolved_issues_count", "error", "created_at", "version", "project_type", "repo_id", "container_id", "claimed_by", "claimed_at", "lease_expires_at", "attempts") SELECT "id", "branch", "sub_path", "status", "required_agent_label", "sbom", "cves", "summary", "duration_ms", "findings_count", "new_issues_count", "resolved_issues_count", "error", "created_at", "version", "project_type", "repo_id", "container_id", "claimed_by", "claimed_at", "lease_expires_at", "attempts" FROM "t_scan"`);
        await queryRunner.query(`DROP TABLE "t_scan"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_scan" RENAME TO "t_scan"`);
        await queryRunner.query(`CREATE INDEX "idx_scan_file" ON "t_scan" ("status", "required_agent_label", "created_at", "id") `);
        await queryRunner.query(`CREATE TABLE "temporary_t_ai_review_result" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "model" varchar(255) NOT NULL, "prompt" text NOT NULL, "response" text, "status" varchar(50) NOT NULL, "error" varchar(500), "created_at" datetime NOT NULL, CONSTRAINT "FK_190898f7957c8095dc8056e0b0a" FOREIGN KEY ("scan_id") REFERENCES "t_scan" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_ai_review_result"("id", "scan_id", "model", "prompt", "response", "status", "error", "created_at") SELECT "id", "scan_id", "model", "prompt", "response", "status", "error", "created_at" FROM "t_ai_review_result"`);
        await queryRunner.query(`DROP TABLE "t_ai_review_result"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_ai_review_result" RENAME TO "t_ai_review_result"`);
        await queryRunner.query(`CREATE TABLE "temporary_t_issue" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "repo_id" integer, "container_id" integer, "fingerprint" varchar(64) NOT NULL, "type" varchar(50) NOT NULL, "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50), "severity" varchar(50), "epss_score" real, "is_kev" boolean NOT NULL DEFAULT (0), "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "description" text, "state" varchar(20) NOT NULL DEFAULT ('open'), "first_seen_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "resolved_at" datetime, "first_seen_scan_id" integer, "last_seen_scan_id" integer, "times_seen" integer NOT NULL DEFAULT (1), "triage_status" varchar(30) NOT NULL DEFAULT ('under_review'), "triage_justification" varchar(64), "triage_comment" text, "triaged_by" varchar(255), "triaged_at" datetime, "triage_expires_at" datetime, "is_direct_dependency" boolean, "line" integer, "ticket_ref" varchar(64), "ticket_url" varchar(500), CONSTRAINT "FK_01a203aba68ef01798fa1831006" FOREIGN KEY ("container_id") REFERENCES "t_container" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_1e46a44f5a6b82dee9f0512b391" FOREIGN KEY ("first_seen_scan_id") REFERENCES "t_scan" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_c2ec84da46d6bbdd89e90b8a275" FOREIGN KEY ("last_seen_scan_id") REFERENCES "t_scan" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_0c779d2cdae6bdf8d243a6435eb" FOREIGN KEY ("repo_id") REFERENCES "t_repository" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_issue"("id", "repo_id", "container_id", "fingerprint", "type", "identifier", "package_name", "package_version", "purl", "file_path", "source", "severity", "epss_score", "is_kev", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "description", "state", "first_seen_at", "last_seen_at", "resolved_at", "first_seen_scan_id", "last_seen_scan_id", "times_seen", "triage_status", "triage_justification", "triage_comment", "triaged_by", "triaged_at", "triage_expires_at", "is_direct_dependency", "line", "ticket_ref", "ticket_url") SELECT "id", "repo_id", "container_id", "fingerprint", "type", "identifier", "package_name", "package_version", "purl", "file_path", "source", "severity", "epss_score", "is_kev", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "description", "state", "first_seen_at", "last_seen_at", "resolved_at", "first_seen_scan_id", "last_seen_scan_id", "times_seen", "triage_status", "triage_justification", "triage_comment", "triaged_by", "triaged_at", "triage_expires_at", "is_direct_dependency", "line", "ticket_ref", "ticket_url" FROM "t_issue"`);
        await queryRunner.query(`DROP TABLE "t_issue"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_issue" RENAME TO "t_issue"`);
        await queryRunner.query(`CREATE TABLE "temporary_t_finding" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "type" varchar(50) NOT NULL, "severity" varchar(50), "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50) NOT NULL, "epss_score" real, "is_kev" boolean NOT NULL, "created_at" datetime NOT NULL, "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "issue_id" integer, "is_direct_dependency" boolean, "line" integer, "description" text, CONSTRAINT "FK_9cb86eaf04924a35b371df9d499" FOREIGN KEY ("issue_id") REFERENCES "t_issue" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_ce962aa8ce0728c834fb2b70caf" FOREIGN KEY ("scan_id") REFERENCES "t_scan" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_finding"("id", "scan_id", "type", "severity", "identifier", "package_name", "package_version", "purl", "file_path", "source", "epss_score", "is_kev", "created_at", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "issue_id", "is_direct_dependency", "line", "description") SELECT "id", "scan_id", "type", "severity", "identifier", "package_name", "package_version", "purl", "file_path", "source", "epss_score", "is_kev", "created_at", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "issue_id", "is_direct_dependency", "line", "description" FROM "t_finding"`);
        await queryRunner.query(`DROP TABLE "t_finding"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_finding" RENAME TO "t_finding"`);
        await queryRunner.query(`CREATE TABLE "temporary_t_session" ("token" varchar(64) PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "created_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "expires_at" datetime NOT NULL, "user_agent" varchar(255), "ip_address" varchar(64), CONSTRAINT "FK_a5f9f098beacf17f45b99b245d2" FOREIGN KEY ("user_id") REFERENCES "t_user" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_t_session"("token", "user_id", "created_at", "last_seen_at", "expires_at", "user_agent", "ip_address") SELECT "token", "user_id", "created_at", "last_seen_at", "expires_at", "user_agent", "ip_address" FROM "t_session"`);
        await queryRunner.query(`DROP TABLE "t_session"`);
        await queryRunner.query(`ALTER TABLE "temporary_t_session" RENAME TO "t_session"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "t_session" RENAME TO "temporary_t_session"`);
        await queryRunner.query(`CREATE TABLE "t_session" ("token" varchar(64) PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "created_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "expires_at" datetime NOT NULL, "user_agent" varchar(255), "ip_address" varchar(64))`);
        await queryRunner.query(`INSERT INTO "t_session"("token", "user_id", "created_at", "last_seen_at", "expires_at", "user_agent", "ip_address") SELECT "token", "user_id", "created_at", "last_seen_at", "expires_at", "user_agent", "ip_address" FROM "temporary_t_session"`);
        await queryRunner.query(`DROP TABLE "temporary_t_session"`);
        await queryRunner.query(`ALTER TABLE "t_finding" RENAME TO "temporary_t_finding"`);
        await queryRunner.query(`CREATE TABLE "t_finding" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "type" varchar(50) NOT NULL, "severity" varchar(50), "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50) NOT NULL, "epss_score" real, "is_kev" boolean NOT NULL, "created_at" datetime NOT NULL, "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "issue_id" integer, "is_direct_dependency" boolean, "line" integer, "description" text)`);
        await queryRunner.query(`INSERT INTO "t_finding"("id", "scan_id", "type", "severity", "identifier", "package_name", "package_version", "purl", "file_path", "source", "epss_score", "is_kev", "created_at", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "issue_id", "is_direct_dependency", "line", "description") SELECT "id", "scan_id", "type", "severity", "identifier", "package_name", "package_version", "purl", "file_path", "source", "epss_score", "is_kev", "created_at", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "issue_id", "is_direct_dependency", "line", "description" FROM "temporary_t_finding"`);
        await queryRunner.query(`DROP TABLE "temporary_t_finding"`);
        await queryRunner.query(`ALTER TABLE "t_issue" RENAME TO "temporary_t_issue"`);
        await queryRunner.query(`CREATE TABLE "t_issue" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "repo_id" integer, "container_id" integer, "fingerprint" varchar(64) NOT NULL, "type" varchar(50) NOT NULL, "identifier" varchar(255), "package_name" varchar(255), "package_version" varchar(255), "purl" varchar(255), "file_path" varchar(500), "source" varchar(50), "severity" varchar(50), "epss_score" real, "is_kev" boolean NOT NULL DEFAULT (0), "cvss_score" real, "cvss_vector" varchar(255), "fix_state" varchar(50), "fix_versions" varchar(255), "link" varchar(500), "description" text, "state" varchar(20) NOT NULL DEFAULT ('open'), "first_seen_at" datetime NOT NULL, "last_seen_at" datetime NOT NULL, "resolved_at" datetime, "first_seen_scan_id" integer, "last_seen_scan_id" integer, "times_seen" integer NOT NULL DEFAULT (1), "triage_status" varchar(30) NOT NULL DEFAULT ('under_review'), "triage_justification" varchar(64), "triage_comment" text, "triaged_by" varchar(255), "triaged_at" datetime, "triage_expires_at" datetime, "is_direct_dependency" boolean, "line" integer, "ticket_ref" varchar(64), "ticket_url" varchar(500))`);
        await queryRunner.query(`INSERT INTO "t_issue"("id", "repo_id", "container_id", "fingerprint", "type", "identifier", "package_name", "package_version", "purl", "file_path", "source", "severity", "epss_score", "is_kev", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "description", "state", "first_seen_at", "last_seen_at", "resolved_at", "first_seen_scan_id", "last_seen_scan_id", "times_seen", "triage_status", "triage_justification", "triage_comment", "triaged_by", "triaged_at", "triage_expires_at", "is_direct_dependency", "line", "ticket_ref", "ticket_url") SELECT "id", "repo_id", "container_id", "fingerprint", "type", "identifier", "package_name", "package_version", "purl", "file_path", "source", "severity", "epss_score", "is_kev", "cvss_score", "cvss_vector", "fix_state", "fix_versions", "link", "description", "state", "first_seen_at", "last_seen_at", "resolved_at", "first_seen_scan_id", "last_seen_scan_id", "times_seen", "triage_status", "triage_justification", "triage_comment", "triaged_by", "triaged_at", "triage_expires_at", "is_direct_dependency", "line", "ticket_ref", "ticket_url" FROM "temporary_t_issue"`);
        await queryRunner.query(`DROP TABLE "temporary_t_issue"`);
        await queryRunner.query(`ALTER TABLE "t_ai_review_result" RENAME TO "temporary_t_ai_review_result"`);
        await queryRunner.query(`CREATE TABLE "t_ai_review_result" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scan_id" integer NOT NULL, "model" varchar(255) NOT NULL, "prompt" text NOT NULL, "response" text, "status" varchar(50) NOT NULL, "error" varchar(500), "created_at" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "t_ai_review_result"("id", "scan_id", "model", "prompt", "response", "status", "error", "created_at") SELECT "id", "scan_id", "model", "prompt", "response", "status", "error", "created_at" FROM "temporary_t_ai_review_result"`);
        await queryRunner.query(`DROP TABLE "temporary_t_ai_review_result"`);
        await queryRunner.query(`DROP INDEX "idx_scan_file"`);
        await queryRunner.query(`ALTER TABLE "t_scan" RENAME TO "temporary_t_scan"`);
        await queryRunner.query(`CREATE TABLE "t_scan" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "status" varchar(255) NOT NULL, "required_agent_label" varchar(255), "sbom" json, "cves" json, "summary" json, "duration_ms" bigint, "findings_count" integer NOT NULL DEFAULT (0), "new_issues_count" integer NOT NULL DEFAULT (0), "resolved_issues_count" integer NOT NULL DEFAULT (0), "error" text, "created_at" datetime NOT NULL, "version" varchar(255), "project_type" varchar(255), "repo_id" integer, "container_id" integer, "claimed_by" varchar(64), "claimed_at" datetime, "lease_expires_at" datetime, "attempts" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "t_scan"("id", "branch", "sub_path", "status", "required_agent_label", "sbom", "cves", "summary", "duration_ms", "findings_count", "new_issues_count", "resolved_issues_count", "error", "created_at", "version", "project_type", "repo_id", "container_id", "claimed_by", "claimed_at", "lease_expires_at", "attempts") SELECT "id", "branch", "sub_path", "status", "required_agent_label", "sbom", "cves", "summary", "duration_ms", "findings_count", "new_issues_count", "resolved_issues_count", "error", "created_at", "version", "project_type", "repo_id", "container_id", "claimed_by", "claimed_at", "lease_expires_at", "attempts" FROM "temporary_t_scan"`);
        await queryRunner.query(`DROP TABLE "temporary_t_scan"`);
        await queryRunner.query(`CREATE INDEX "idx_scan_file" ON "t_scan" ("status", "required_agent_label", "created_at", "id") `);
        await queryRunner.query(`ALTER TABLE "t_repository" RENAME TO "temporary_t_repository"`);
        await queryRunner.query(`CREATE TABLE "t_repository" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "url" varchar(255) NOT NULL, "branch" varchar(255) NOT NULL, "sub_path" varchar(255), "required_agent_label" varchar(255), "name" varchar(255), "scan_interval_minutes" integer, "scan_cron" varchar(255), "last_scheduled_scan_at" datetime, "ssh_key_id" varchar(36))`);
        await queryRunner.query(`INSERT INTO "t_repository"("id", "url", "branch", "sub_path", "required_agent_label", "name", "scan_interval_minutes", "scan_cron", "last_scheduled_scan_at", "ssh_key_id") SELECT "id", "url", "branch", "sub_path", "required_agent_label", "name", "scan_interval_minutes", "scan_cron", "last_scheduled_scan_at", "ssh_key_id" FROM "temporary_t_repository"`);
        await queryRunner.query(`DROP TABLE "temporary_t_repository"`);
        await queryRunner.query(`ALTER TABLE "t_agent" RENAME TO "temporary_t_agent"`);
        await queryRunner.query(`CREATE TABLE "t_agent" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" varchar(500), "kind" varchar(20) NOT NULL, "labels" varchar(255), "credentials_mode" varchar(20) NOT NULL, "enabled" boolean NOT NULL, "max_concurrent" integer, "api_key_id" varchar(36), "hostname" varchar(255), "platform" varchar(255), "version" varchar(50), "scanner_engine" varchar(50), "sealing_public_key" varchar(255), "capabilities" json, "contract_version" varchar(20), "last_seen_at" datetime, "created_at" datetime NOT NULL)`);
        await queryRunner.query(`INSERT INTO "t_agent"("id", "name", "description", "kind", "labels", "credentials_mode", "enabled", "max_concurrent", "api_key_id", "hostname", "platform", "version", "scanner_engine", "sealing_public_key", "capabilities", "contract_version", "last_seen_at", "created_at") SELECT "id", "name", "description", "kind", "labels", "credentials_mode", "enabled", "max_concurrent", "api_key_id", "hostname", "platform", "version", "scanner_engine", "sealing_public_key", "capabilities", "contract_version", "last_seen_at", "created_at" FROM "temporary_t_agent"`);
        await queryRunner.query(`DROP TABLE "temporary_t_agent"`);
        await queryRunner.query(`DROP TABLE "t_setting"`);
        await queryRunner.query(`DROP TABLE "t_session"`);
        await queryRunner.query(`DROP TABLE "t_user"`);
        await queryRunner.query(`DROP TABLE "t_processed_message"`);
        await queryRunner.query(`DROP TABLE "t_outbox_message"`);
        await queryRunner.query(`DROP TABLE "t_login_attempt"`);
        await queryRunner.query(`DROP TABLE "t_leader_lease"`);
        await queryRunner.query(`DROP TABLE "t_gate_policy"`);
        await queryRunner.query(`DROP TABLE "t_finding"`);
        await queryRunner.query(`DROP TABLE "t_issue"`);
        await queryRunner.query(`DROP INDEX "idx_audit_log_ordre"`);
        await queryRunner.query(`DROP TABLE "t_audit_log"`);
        await queryRunner.query(`DROP TABLE "t_ai_review_result"`);
        await queryRunner.query(`DROP INDEX "idx_scan_file"`);
        await queryRunner.query(`DROP TABLE "t_scan"`);
        await queryRunner.query(`DROP TABLE "t_repository"`);
        await queryRunner.query(`DROP TABLE "t_ssh_key"`);
        await queryRunner.query(`DROP TABLE "t_container"`);
        await queryRunner.query(`DROP TABLE "t_agent"`);
        await queryRunner.query(`DROP TABLE "t_api_key"`);
    }

}
