import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1786512563084 implements MigrationInterface {
    name = 'Baseline1786512563084'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "t_api_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "key_hash" character varying(255) NOT NULL, "prefix" character varying(16), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_used_at" TIMESTAMP WITH TIME ZONE, "scopes" character varying(255) NOT NULL DEFAULT 'read,scan,export', "target_kind" character varying(20), "target_id" integer, "expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cf365581caf58b681a88a614bda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_agent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(500), "kind" character varying(20) NOT NULL, "labels" character varying(255), "credentials_mode" character varying(20) NOT NULL, "enabled" boolean NOT NULL, "max_concurrent" integer, "api_key_id" uuid, "hostname" character varying(255), "platform" character varying(255), "version" character varying(50), "scanner_engine" character varying(50), "capabilities" json, "contract_version" character varying(20), "last_seen_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_d0e592c217759feb70e0125cd46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_container" ("id" SERIAL NOT NULL, "registry" character varying(255), "image_name" character varying(255) NOT NULL, "tag" character varying(255) NOT NULL, "scan_interval_minutes" integer, "scan_cron" character varying(255), "last_scheduled_scan_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2ff55e28684f30b2f145407fd43" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_ssh_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "private_key" text NOT NULL, "public_key" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_019ba2f4e5561396c0d9afa9fef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_repository" ("id" SERIAL NOT NULL, "url" character varying(255) NOT NULL, "branch" character varying(255) NOT NULL, "sub_path" character varying(255), "name" character varying(255), "scan_interval_minutes" integer, "scan_cron" character varying(255), "last_scheduled_scan_at" TIMESTAMP WITH TIME ZONE, "ssh_key_id" uuid, CONSTRAINT "PK_aa6233aa81b80fa41ce30b57edf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_scan" ("id" SERIAL NOT NULL, "branch" character varying(255) NOT NULL, "sub_path" character varying(255), "status" character varying(255) NOT NULL, "sbom" json, "cves" json, "summary" json, "duration_ms" bigint, "findings_count" integer NOT NULL DEFAULT '0', "new_issues_count" integer NOT NULL DEFAULT '0', "resolved_issues_count" integer NOT NULL DEFAULT '0', "error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "version" character varying(255), "project_type" character varying(255), "repo_id" integer, "container_id" integer, "claimed_by" character varying(64), "claimed_at" TIMESTAMP WITH TIME ZONE, "lease_expires_at" TIMESTAMP WITH TIME ZONE, "attempts" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_53a1ee59c5168445835a65aaac7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_ai_review_result" ("id" SERIAL NOT NULL, "scan_id" integer NOT NULL, "model" character varying(255) NOT NULL, "prompt" text NOT NULL, "response" text, "status" character varying(50) NOT NULL, "error" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_7b3ac32ae55200092be33927980" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying(255) NOT NULL, "operation_type" character varying(255) NOT NULL, "resource_id" character varying(255) NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" character varying(255), "ip_address" character varying(64), "user_agent" character varying(255), "previous_hash" character varying(64), "entry_hash" character varying(64), CONSTRAINT "PK_550f75d3f507e43aad9dc2431ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_issue" ("id" SERIAL NOT NULL, "repo_id" integer, "container_id" integer, "fingerprint" character varying(64) NOT NULL, "type" character varying(50) NOT NULL, "identifier" character varying(255), "package_name" character varying(255), "package_version" character varying(255), "purl" character varying(255), "file_path" character varying(500), "source" character varying(50), "severity" character varying(50), "epss_score" double precision, "is_kev" boolean NOT NULL DEFAULT false, "cvss_score" double precision, "cvss_vector" character varying(255), "fix_state" character varying(50), "fix_versions" character varying(255), "link" character varying(500), "description" text, "state" character varying(20) NOT NULL DEFAULT 'open', "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "resolved_at" TIMESTAMP WITH TIME ZONE, "first_seen_scan_id" integer, "last_seen_scan_id" integer, "times_seen" integer NOT NULL DEFAULT '1', "triage_status" character varying(30) NOT NULL DEFAULT 'under_review', "triage_justification" character varying(64), "triage_comment" text, "triaged_by" character varying(255), "triaged_at" TIMESTAMP WITH TIME ZONE, "triage_expires_at" TIMESTAMP WITH TIME ZONE, "is_direct_dependency" boolean, "line" integer, "ticket_ref" character varying(64), "ticket_url" character varying(500), CONSTRAINT "PK_42ca02999bc7ac75f8acf223d77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_finding" ("id" SERIAL NOT NULL, "scan_id" integer NOT NULL, "type" character varying(50) NOT NULL, "severity" character varying(50), "identifier" character varying(255), "package_name" character varying(255), "package_version" character varying(255), "purl" character varying(255), "file_path" character varying(500), "source" character varying(50) NOT NULL, "epss_score" double precision, "is_kev" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "cvss_score" double precision, "cvss_vector" character varying(255), "fix_state" character varying(50), "fix_versions" character varying(255), "link" character varying(500), "issue_id" integer, "is_direct_dependency" boolean, "line" integer, "description" text, CONSTRAINT "PK_1e0b306032a44a06a9c3991c822" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_gate_policy" ("id" SERIAL NOT NULL, "target_kind" character varying(20) NOT NULL, "target_id" integer NOT NULL, "version" integer NOT NULL, "is_active" boolean, "fail_on_severity" character varying(20), "fail_on_kev" boolean NOT NULL, "fixable_only" boolean NOT NULL, "include_triaged" boolean NOT NULL, "include_ai_review" boolean NOT NULL, "note" text, "created_by" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_f0f65845bcad3d1aa00aff0a21e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_leader_lease" ("name" character varying(64) NOT NULL, "holder" character varying(64), "acquired_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_434b29bb2afc57328fd379d9435" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "t_login_attempt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "counter_key" character varying(255) NOT NULL, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_5b2e672fad0f5a9c3464a4d847d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_outbox_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_type" character varying(50) NOT NULL, "payload" json NOT NULL, "status" character varying(20) NOT NULL, "attempts" integer NOT NULL, "next_attempt_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1ebbd05ba933d6d271d4b964229" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_processed_message" ("id" SERIAL NOT NULL, "message_id" character varying(64) NOT NULL, "message_type" character varying(50) NOT NULL, "agent_id" uuid, "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_5a3db5fae0f617b55e21654d61f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_user" ("id" SERIAL NOT NULL, "username" character varying(255) NOT NULL, "email" character varying(255), "password" character varying(255), "display_name" character varying(255), "avatar_url" character varying(255), "role" character varying(255) NOT NULL, "is_active" boolean NOT NULL, "github_id" character varying(255), "keycloak_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "must_change_password" boolean NOT NULL, CONSTRAINT "UQ_cebdcd668896f79744000f50dd3" UNIQUE ("username"), CONSTRAINT "UQ_1d0b42896fa20240f9ffcc8012a" UNIQUE ("email"), CONSTRAINT "UQ_16391e9a0f1e1b6e286ec6ff9ba" UNIQUE ("github_id"), CONSTRAINT "UQ_43acce0aa9f45484164891a5489" UNIQUE ("keycloak_id"), CONSTRAINT "PK_6a6708d647ac5da9ab8271cfede" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "t_session" ("token" character varying(64) NOT NULL, "user_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_agent" character varying(255), "ip_address" character varying(64), CONSTRAINT "PK_bdc79a12b77624afcf069383d88" PRIMARY KEY ("token"))`);
        await queryRunner.query(`CREATE TABLE "t_setting" ("key" character varying(255) NOT NULL, "value" character varying(255), CONSTRAINT "PK_2da0aa23bee7f186f4bcdb6ba7e" PRIMARY KEY ("key"))`);
        await queryRunner.query(`ALTER TABLE "t_agent" ADD CONSTRAINT "FK_28216d89bbec1752bb00c82fb3d" FOREIGN KEY ("api_key_id") REFERENCES "t_api_key"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_repository" ADD CONSTRAINT "FK_154e4f287a89244dd8e19591fde" FOREIGN KEY ("ssh_key_id") REFERENCES "t_ssh_key"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_scan" ADD CONSTRAINT "FK_d6f19b8301b5a4aeb38208bc219" FOREIGN KEY ("container_id") REFERENCES "t_container"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_scan" ADD CONSTRAINT "FK_a8c35b7077df870971f96c6ec05" FOREIGN KEY ("repo_id") REFERENCES "t_repository"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_ai_review_result" ADD CONSTRAINT "FK_190898f7957c8095dc8056e0b0a" FOREIGN KEY ("scan_id") REFERENCES "t_scan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_issue" ADD CONSTRAINT "FK_01a203aba68ef01798fa1831006" FOREIGN KEY ("container_id") REFERENCES "t_container"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_issue" ADD CONSTRAINT "FK_1e46a44f5a6b82dee9f0512b391" FOREIGN KEY ("first_seen_scan_id") REFERENCES "t_scan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_issue" ADD CONSTRAINT "FK_c2ec84da46d6bbdd89e90b8a275" FOREIGN KEY ("last_seen_scan_id") REFERENCES "t_scan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_issue" ADD CONSTRAINT "FK_0c779d2cdae6bdf8d243a6435eb" FOREIGN KEY ("repo_id") REFERENCES "t_repository"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_finding" ADD CONSTRAINT "FK_9cb86eaf04924a35b371df9d499" FOREIGN KEY ("issue_id") REFERENCES "t_issue"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_finding" ADD CONSTRAINT "FK_ce962aa8ce0728c834fb2b70caf" FOREIGN KEY ("scan_id") REFERENCES "t_scan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "t_session" ADD CONSTRAINT "FK_a5f9f098beacf17f45b99b245d2" FOREIGN KEY ("user_id") REFERENCES "t_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "t_session" DROP CONSTRAINT "FK_a5f9f098beacf17f45b99b245d2"`);
        await queryRunner.query(`ALTER TABLE "t_finding" DROP CONSTRAINT "FK_ce962aa8ce0728c834fb2b70caf"`);
        await queryRunner.query(`ALTER TABLE "t_finding" DROP CONSTRAINT "FK_9cb86eaf04924a35b371df9d499"`);
        await queryRunner.query(`ALTER TABLE "t_issue" DROP CONSTRAINT "FK_0c779d2cdae6bdf8d243a6435eb"`);
        await queryRunner.query(`ALTER TABLE "t_issue" DROP CONSTRAINT "FK_c2ec84da46d6bbdd89e90b8a275"`);
        await queryRunner.query(`ALTER TABLE "t_issue" DROP CONSTRAINT "FK_1e46a44f5a6b82dee9f0512b391"`);
        await queryRunner.query(`ALTER TABLE "t_issue" DROP CONSTRAINT "FK_01a203aba68ef01798fa1831006"`);
        await queryRunner.query(`ALTER TABLE "t_ai_review_result" DROP CONSTRAINT "FK_190898f7957c8095dc8056e0b0a"`);
        await queryRunner.query(`ALTER TABLE "t_scan" DROP CONSTRAINT "FK_a8c35b7077df870971f96c6ec05"`);
        await queryRunner.query(`ALTER TABLE "t_scan" DROP CONSTRAINT "FK_d6f19b8301b5a4aeb38208bc219"`);
        await queryRunner.query(`ALTER TABLE "t_repository" DROP CONSTRAINT "FK_154e4f287a89244dd8e19591fde"`);
        await queryRunner.query(`ALTER TABLE "t_agent" DROP CONSTRAINT "FK_28216d89bbec1752bb00c82fb3d"`);
        await queryRunner.query(`DROP TABLE "t_setting"`);
        await queryRunner.query(`DROP TABLE "t_session"`);
        await queryRunner.query(`DROP TABLE "t_user"`);
        await queryRunner.query(`DROP TABLE "t_processed_message"`);
        await queryRunner.query(`DROP TABLE "t_outbox_message"`);
        await queryRunner.query(`DROP TABLE "t_login_attempt"`);
        await queryRunner.query(`DROP TABLE "t_leader_lease"`);
        await queryRunner.query(`DROP TABLE "t_gate_policy"`);
        await queryRunner.query(`DROP TABLE "t_finding"`);
        await queryRunner.query(`DROP TABLE "t_issue"`);
        await queryRunner.query(`DROP TABLE "t_audit_log"`);
        await queryRunner.query(`DROP TABLE "t_ai_review_result"`);
        await queryRunner.query(`DROP TABLE "t_scan"`);
        await queryRunner.query(`DROP TABLE "t_repository"`);
        await queryRunner.query(`DROP TABLE "t_ssh_key"`);
        await queryRunner.query(`DROP TABLE "t_container"`);
        await queryRunner.query(`DROP TABLE "t_agent"`);
        await queryRunner.query(`DROP TABLE "t_api_key"`);
    }

}
