import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1786512089042 implements MigrationInterface {
    name = 'Baseline1786512089042'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "api_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "key_hash" character varying(255) NOT NULL, "prefix" character varying(16), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_used_at" TIMESTAMP WITH TIME ZONE, "scopes" character varying(255) NOT NULL DEFAULT 'read,scan,export', "target_kind" character varying(20), "target_id" integer, "expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b1bd840641b8acbaad89c3d8d11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(500), "kind" character varying(20) NOT NULL, "labels" character varying(255), "credentials_mode" character varying(20) NOT NULL, "enabled" boolean NOT NULL, "max_concurrent" integer, "api_key_id" uuid, "hostname" character varying(255), "platform" character varying(255), "version" character varying(50), "scanner_engine" character varying(50), "capabilities" json, "contract_version" character varying(20), "last_seen_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_1000e989398c5d4ed585cf9a46f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "container" ("id" SERIAL NOT NULL, "registry" character varying(255), "image_name" character varying(255) NOT NULL, "tag" character varying(255) NOT NULL, "scan_interval_minutes" integer, "scan_cron" character varying(255), "last_scheduled_scan_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_74656f796df3346fa6ec89fa727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ssh_key" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "private_key" text NOT NULL, "public_key" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_a8151d9d1fd8357c7a33fa2b342" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "repository" ("id" SERIAL NOT NULL, "url" character varying(255) NOT NULL, "branch" character varying(255) NOT NULL, "sub_path" character varying(255), "name" character varying(255), "scan_interval_minutes" integer, "scan_cron" character varying(255), "last_scheduled_scan_at" TIMESTAMP WITH TIME ZONE, "ssh_key_id" uuid, CONSTRAINT "PK_b842c26651c6fc0b9ccd1c530e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scan" ("id" SERIAL NOT NULL, "branch" character varying(255) NOT NULL, "sub_path" character varying(255), "status" character varying(255) NOT NULL, "sbom" json, "cves" json, "summary" json, "duration_ms" bigint, "findings_count" integer NOT NULL DEFAULT '0', "new_issues_count" integer NOT NULL DEFAULT '0', "resolved_issues_count" integer NOT NULL DEFAULT '0', "error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "version" character varying(255), "project_type" character varying(255), "repo_id" integer, "container_id" integer, "claimed_by" character varying(64), "claimed_at" TIMESTAMP WITH TIME ZONE, "lease_expires_at" TIMESTAMP WITH TIME ZONE, "attempts" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_9868a638d0569ba3fe3bddcef84" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_review_result" ("id" SERIAL NOT NULL, "scan_id" integer NOT NULL, "model" character varying(255) NOT NULL, "prompt" text NOT NULL, "response" text, "status" character varying(50) NOT NULL, "error" character varying(500), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_38dc3eeb86b4a9bb2aff1a56d9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "description" character varying(255) NOT NULL, "operation_type" character varying(255) NOT NULL, "resource_id" character varying(255) NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "user_id" character varying(255), "ip_address" character varying(64), "user_agent" character varying(255), "previous_hash" character varying(64), "entry_hash" character varying(64), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "issue" ("id" SERIAL NOT NULL, "repo_id" integer, "container_id" integer, "fingerprint" character varying(64) NOT NULL, "type" character varying(50) NOT NULL, "identifier" character varying(255), "package_name" character varying(255), "package_version" character varying(255), "purl" character varying(255), "file_path" character varying(500), "source" character varying(50), "severity" character varying(50), "epss_score" double precision, "is_kev" boolean NOT NULL DEFAULT false, "cvss_score" double precision, "cvss_vector" character varying(255), "fix_state" character varying(50), "fix_versions" character varying(255), "link" character varying(500), "description" text, "state" character varying(20) NOT NULL DEFAULT 'open', "first_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "resolved_at" TIMESTAMP WITH TIME ZONE, "first_seen_scan_id" integer, "last_seen_scan_id" integer, "times_seen" integer NOT NULL DEFAULT '1', "triage_status" character varying(30) NOT NULL DEFAULT 'under_review', "triage_justification" character varying(64), "triage_comment" text, "triaged_by" character varying(255), "triaged_at" TIMESTAMP WITH TIME ZONE, "triage_expires_at" TIMESTAMP WITH TIME ZONE, "is_direct_dependency" boolean, "line" integer, "ticket_ref" character varying(64), "ticket_url" character varying(500), CONSTRAINT "PK_f80e086c249b9f3f3ff2fd321b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finding" ("id" SERIAL NOT NULL, "scan_id" integer NOT NULL, "type" character varying(50) NOT NULL, "severity" character varying(50), "identifier" character varying(255), "package_name" character varying(255), "package_version" character varying(255), "purl" character varying(255), "file_path" character varying(500), "source" character varying(50) NOT NULL, "epss_score" double precision, "is_kev" boolean NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "cvss_score" double precision, "cvss_vector" character varying(255), "fix_state" character varying(50), "fix_versions" character varying(255), "link" character varying(500), "issue_id" integer, "is_direct_dependency" boolean, "line" integer, "description" text, CONSTRAINT "PK_a904dfcf401ccfbaa60bb6eec29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "gate_policy" ("id" SERIAL NOT NULL, "target_kind" character varying(20) NOT NULL, "target_id" integer NOT NULL, "version" integer NOT NULL, "is_active" boolean, "fail_on_severity" character varying(20), "fail_on_kev" boolean NOT NULL, "fixable_only" boolean NOT NULL, "include_triaged" boolean NOT NULL, "include_ai_review" boolean NOT NULL, "note" text, "created_by" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_ac61ff04295cf52a1ab109fa098" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "leader_lease" ("name" character varying(64) NOT NULL, "holder" character varying(64), "acquired_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_c36f90c428fa735db5b91aab9c4" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "login_attempt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "counter_key" character varying(255) NOT NULL, "occurred_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_72829cd4f7424e3cdfd46c476c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "outbox_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_type" character varying(50) NOT NULL, "payload" json NOT NULL, "status" character varying(20) NOT NULL, "attempts" integer NOT NULL, "next_attempt_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2f36ee5236f2793f3e7bd554589" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "processed_message" ("id" SERIAL NOT NULL, "message_id" character varying(64) NOT NULL, "message_type" character varying(50) NOT NULL, "agent_id" uuid, "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8e3fd5041a92cfd8614379458c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "app_user" ("id" SERIAL NOT NULL, "username" character varying(255) NOT NULL, "email" character varying(255), "password" character varying(255), "display_name" character varying(255), "avatar_url" character varying(255), "role" character varying(255) NOT NULL, "is_active" boolean NOT NULL, "github_id" character varying(255), "keycloak_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "must_change_password" boolean NOT NULL, CONSTRAINT "UQ_c480e576dd71729addbc2d51b67" UNIQUE ("username"), CONSTRAINT "UQ_3fa909d0e37c531ebc237703391" UNIQUE ("email"), CONSTRAINT "UQ_34d17fd94fe3ec79f2709fa9e1b" UNIQUE ("github_id"), CONSTRAINT "UQ_6e1d1a6bf254ffa99033e1d7426" UNIQUE ("keycloak_id"), CONSTRAINT "PK_22a5c4a3d9b2fb8e4e73fc4ada1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("token" character varying(64) NOT NULL, "user_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "last_seen_at" TIMESTAMP WITH TIME ZONE NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "user_agent" character varying(255), "ip_address" character varying(64), CONSTRAINT "PK_232f8e85d7633bd6ddfad421696" PRIMARY KEY ("token"))`);
        await queryRunner.query(`CREATE TABLE "setting" ("key" character varying(255) NOT NULL, "value" character varying(255), CONSTRAINT "PK_1c4c95d773004250c157a744d6e" PRIMARY KEY ("key"))`);
        await queryRunner.query(`ALTER TABLE "agent" ADD CONSTRAINT "FK_1676e74cb3f60757fc5854e27eb" FOREIGN KEY ("api_key_id") REFERENCES "api_key"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repository" ADD CONSTRAINT "FK_b7c5a997db9b0b9e36f5cad5431" FOREIGN KEY ("ssh_key_id") REFERENCES "ssh_key"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan" ADD CONSTRAINT "FK_260c81581a721bd5dac463d3299" FOREIGN KEY ("container_id") REFERENCES "container"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scan" ADD CONSTRAINT "FK_43b80f586cebc5941f4a08c6f77" FOREIGN KEY ("repo_id") REFERENCES "repository"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_review_result" ADD CONSTRAINT "FK_3ad57cc6e4b912241aae8241fb7" FOREIGN KEY ("scan_id") REFERENCES "scan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_4aa7893735818b3f308ab58f48e" FOREIGN KEY ("container_id") REFERENCES "container"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_69f15d493fa4265779ee9092dc1" FOREIGN KEY ("first_seen_scan_id") REFERENCES "scan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_4d9f4d2aaebef9960230594d90d" FOREIGN KEY ("last_seen_scan_id") REFERENCES "scan"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue" ADD CONSTRAINT "FK_f82f23e56c6b071adea21abf588" FOREIGN KEY ("repo_id") REFERENCES "repository"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finding" ADD CONSTRAINT "FK_971747d142ce03380707d2a9fd2" FOREIGN KEY ("issue_id") REFERENCES "issue"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finding" ADD CONSTRAINT "FK_d1819b8d59845c251aaf42dca6f" FOREIGN KEY ("scan_id") REFERENCES "scan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "app_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`);
        await queryRunner.query(`ALTER TABLE "finding" DROP CONSTRAINT "FK_d1819b8d59845c251aaf42dca6f"`);
        await queryRunner.query(`ALTER TABLE "finding" DROP CONSTRAINT "FK_971747d142ce03380707d2a9fd2"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_f82f23e56c6b071adea21abf588"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_4d9f4d2aaebef9960230594d90d"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_69f15d493fa4265779ee9092dc1"`);
        await queryRunner.query(`ALTER TABLE "issue" DROP CONSTRAINT "FK_4aa7893735818b3f308ab58f48e"`);
        await queryRunner.query(`ALTER TABLE "ai_review_result" DROP CONSTRAINT "FK_3ad57cc6e4b912241aae8241fb7"`);
        await queryRunner.query(`ALTER TABLE "scan" DROP CONSTRAINT "FK_43b80f586cebc5941f4a08c6f77"`);
        await queryRunner.query(`ALTER TABLE "scan" DROP CONSTRAINT "FK_260c81581a721bd5dac463d3299"`);
        await queryRunner.query(`ALTER TABLE "repository" DROP CONSTRAINT "FK_b7c5a997db9b0b9e36f5cad5431"`);
        await queryRunner.query(`ALTER TABLE "agent" DROP CONSTRAINT "FK_1676e74cb3f60757fc5854e27eb"`);
        await queryRunner.query(`DROP TABLE "setting"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TABLE "app_user"`);
        await queryRunner.query(`DROP TABLE "processed_message"`);
        await queryRunner.query(`DROP TABLE "outbox_message"`);
        await queryRunner.query(`DROP TABLE "login_attempt"`);
        await queryRunner.query(`DROP TABLE "leader_lease"`);
        await queryRunner.query(`DROP TABLE "gate_policy"`);
        await queryRunner.query(`DROP TABLE "finding"`);
        await queryRunner.query(`DROP TABLE "issue"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "ai_review_result"`);
        await queryRunner.query(`DROP TABLE "scan"`);
        await queryRunner.query(`DROP TABLE "repository"`);
        await queryRunner.query(`DROP TABLE "ssh_key"`);
        await queryRunner.query(`DROP TABLE "container"`);
        await queryRunner.query(`DROP TABLE "agent"`);
        await queryRunner.query(`DROP TABLE "api_key"`);
    }

}
