"""baseline schema

The schema as it stood before Alembic was introduced, so that a fresh
deployment can be built from migrations alone.

Existing deployments already have all of these tables (they were created by
`Base.metadata.create_all`, or by an earlier implementation of this
application). They are *stamped* at this revision rather than upgraded to it —
see `zanshin/schema.py`, which detects that case at startup and stamps instead
of replaying this migration onto a populated database.

Revision ID: 0001
Revises:
Create Date: 2026-08-06

Amended after the fact: the foreign key columns below were `BigInteger` while the
primary keys they reference are `Integer`. MySQL refuses that outright, so a fresh
database could not be created there at all. Editing a baseline is safe precisely
because it only ever runs on a fresh database — deployments that already applied the
original are stamped past it and are corrected by migration 0007 instead.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use custom column types (`GUID`, `SafeDateTime`); autogenerate
# renders them by their fully-qualified name, so these modules must be
# importable from every migration.
import zanshin.models.guid
import zanshin.models.safedatetime

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', zanshin.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('last_used_at', zanshin.models.safedatetime.SafeDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', zanshin.models.guid.GUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('operation_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registry', sa.String(length=255), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('scan_cron', sa.String(length=255), nullable=True),
    sa.Column('last_scheduled_scan_at', zanshin.models.safedatetime.SafeDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_id'), ['id'], unique=False)

    op.create_table('setting',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ssh_key',
    sa.Column('id', zanshin.models.guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('keycloak_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('updated_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('keycloak_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('sub_path', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('scan_cron', sa.String(length=255), nullable=True),
    sa.Column('last_scheduled_scan_at', zanshin.models.safedatetime.SafeDateTime(), nullable=True),
    sa.Column('ssh_key_id', zanshin.models.guid.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['ssh_key_id'], ['ssh_key.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repository_id'), ['id'], unique=False)

    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('sub_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('sbom', sa.JSON(), nullable=True),
    sa.Column('cves', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=255), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_id'), ['id'], unique=False)

    op.create_table('vex_decision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=255), nullable=False),
    sa.Column('package_name', sa.String(length=255), nullable=False),
    sa.Column('purl', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('justification', sa.String(length=255), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('updated_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vex_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vex_decision_id'), ['id'], unique=False)

    op.create_table('ai_review_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    with op.batch_alter_table('ai_review_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_review_result_id'), ['id'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('identifier', sa.String(length=255), nullable=True),
    sa.Column('package_name', sa.String(length=255), nullable=True),
    sa.Column('package_version', sa.String(length=255), nullable=True),
    sa.Column('purl', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('is_kev', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('vex_decision_id', sa.Integer(), nullable=True),
    sa.Column('created_at', zanshin.models.safedatetime.SafeDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scan.id'], ),
    sa.ForeignKeyConstraint(['vex_decision_id'], ['vex_decision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_id'))

    op.drop_table('finding')
    with op.batch_alter_table('ai_review_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_review_result_id'))

    op.drop_table('ai_review_result')
    with op.batch_alter_table('vex_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vex_decision_id'))

    op.drop_table('vex_decision')
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_id'))

    op.drop_table('scan')
    with op.batch_alter_table('repository', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repository_id'))

    op.drop_table('repository')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    op.drop_table('ssh_key')
    op.drop_table('setting')
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_container_id'))

    op.drop_table('container')
    op.drop_table('audit_logs')
    op.drop_table('api_key')
    # ### end Alembic commands ###
