"""api key scopes, forced password change, audit context and chain

Adds what the security review found missing, and backfills each column with the
behaviour the rows already had — the rule that keeps a migration from breaking a
running deployment:

- `api_key.scopes` defaults to every scope, because that is exactly what an existing
  key could already do. Narrowing silently would break working pipelines at the next
  request, which is a worse outcome than a key being broader than ideal for one more
  rotation.
- `api_key.target_kind`/`target_id` stay null, i.e. "every target" — again what
  existing keys already had.
- `user.must_change_password` is false for existing accounts: their passwords were
  chosen by their owners, not handed out in an environment file. Only the bootstrap
  account gets it set, at creation.
- The `audit_logs` columns are nullable and left empty for past rows. Backfilling a
  hash chain over history would be fabricating evidence: entries written before the
  chain existed cannot be shown to be untampered, and pretending otherwise is worse
  than an honest gap. The chain starts at the next entry (see AuditLogService).

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-06 14:19:18.533597
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models use custom column types (`GUID`, `SafeDateTime`); autogenerate
# renders them by their fully-qualified name, so these modules must be
# importable from every migration.
import zanshin.models.guid
import zanshin.models.safedatetime

revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add each column only where it is missing.

    Not defensive style for its own sake: a database can genuinely arrive here with
    part of this migration already applied. Alembic treats SQLite DDL as
    non-transactional, so an upgrade interrupted between two `batch_alter_table`
    blocks leaves the columns it added *and* the old version stamp — and a plain
    re-run then dies on "duplicate column", leaving the deployment stuck. Checking
    first makes the migration resumable. (The concurrent start that caused this is
    fixed at the source too, in `zanshin/schema.py`.)
    """
    inspector = sa.inspect(op.get_bind())

    def missing(table: str, column: str) -> bool:
        return column not in {c["name"] for c in inspector.get_columns(table)}

    api_key_columns = [
        ("scopes", sa.Column("scopes", sa.String(length=255), nullable=False,
                             server_default="read,scan,export")),
        ("target_kind", sa.Column("target_kind", sa.String(length=20), nullable=True)),
        ("target_id", sa.Column("target_id", sa.Integer(), nullable=True)),
        ("expires_at", sa.Column("expires_at", zanshin.models.safedatetime.SafeDateTime(), nullable=True)),
    ]
    to_add = [column for name, column in api_key_columns if missing("api_key", name)]
    if to_add:
        with op.batch_alter_table("api_key", schema=None) as batch_op:
            for column in to_add:
                batch_op.add_column(column)

    audit_columns = [
        ("ip_address", sa.Column("ip_address", sa.String(length=64), nullable=True)),
        ("user_agent", sa.Column("user_agent", sa.String(length=255), nullable=True)),
        ("previous_hash", sa.Column("previous_hash", sa.String(length=64), nullable=True)),
        ("entry_hash", sa.Column("entry_hash", sa.String(length=64), nullable=True)),
    ]
    to_add = [column for name, column in audit_columns if missing("audit_logs", name)]
    if to_add:
        with op.batch_alter_table("audit_logs", schema=None) as batch_op:
            for column in to_add:
                batch_op.add_column(column)

    if missing("user", "must_change_password"):
        with op.batch_alter_table("user", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "must_change_password", sa.Boolean(), nullable=False, server_default=sa.false()
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('entry_hash')
        batch_op.drop_column('previous_hash')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_column('expires_at')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_kind')
        batch_op.drop_column('scopes')

    # ### end Alembic commands ###
