package com.asmolabs.vectispire.core.compliance.internal;

import com.asmolabs.vectispire.common.domain.access.Visibility;
import com.asmolabs.vectispire.common.domain.compliance.ScopeCoverage;
import com.asmolabs.vectispire.common.domain.remediation.RemediationDistribution;
import com.asmolabs.vectispire.common.domain.retention.EvidenceRetention;
import com.asmolabs.vectispire.common.domain.rules.RuleCoverage;
import com.asmolabs.vectispire.common.domain.settings.Setting;
import com.asmolabs.vectispire.common.domain.targets.ScanTarget;
import com.asmolabs.vectispire.core.compliance.CertifiedScopeService;
import com.asmolabs.vectispire.core.gate.GateRegisterService;
import com.asmolabs.vectispire.core.gate.GateVerdictView;
import com.asmolabs.vectispire.core.posture.RemediationDistributionService;
import com.asmolabs.vectispire.core.rules.RuleCoverageService;
import com.asmolabs.vectispire.core.services.issues.ExceptionsRegisterService;
import com.asmolabs.vectispire.core.settings.SettingsService;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.time.YearMonth;
import java.time.ZoneOffset;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * The four registers that show a control <em>operated</em>, shaped for an archive rather than a
 * screen.
 *
 * <h2>Why these are not the API responses</h2>
 *
 * <p><b>A screen answers "where do we stand"; an assessor asks "did this run, throughout, and
 * what did it produce".</b> Those want different documents. The register route returns the last
 * hundred verdicts newest-first, which is the right answer for somebody watching a pipeline and
 * the wrong one for somebody auditing a year: a busy estate writes a hundred verdicts before
 * lunch, so that page proves yesterday and nothing else.
 *
 * <p>So the bundle carries the shape an assessment actually tests:
 *
 * <ul>
 *   <li><b>Continuity by month.</b> The single most probative figure in the archive. A month with
 *       no verdicts is a month the control did not operate, and no total can show that — a year
 *       with a silent August and a busy September has an excellent annual number.
 *   <li><b>Every refusal, in full.</b> Passes are evidence of volume and are summarised; refusals
 *       are evidence the control has teeth and are listed. A gate that has never refused anything
 *       is indistinguishable from a gate that is not wired in, and that is the distinction the
 *       document exists to make.
 *   <li><b>What the figures do not cover.</b> See {@link Coverage}.
 * </ul>
 *
 * <h2>Visibility</h2>
 *
 * <p>Every section is narrowed by {@code permits} after a bounded read, like everything else here.
 * A bundle generated by a lead holding a scoped credential describes that scope — and says so, so
 * that a partial archive is never mistaken for the estate's.
 */
@Service
public class ProcessEvidenceService {

    /**
     * How many verdict rows the archive reads.
     *
     * <p>Ten thousand rather than everything: this table grows with the build rate, and a bundle
     * that tries to serialise a year of a busy pipeline exhausts a heap instead of producing a
     * document. Where the cap bites, {@link Coverage} says so rather than letting the period look
     * shorter than it was.
     */
    static final int VERDICT_READ_CAP = 10_000;

    /** Refusals are listed in full up to here; beyond it the archive says how many it dropped. */
    static final int REFUSAL_LIST_CAP = 2_000;

    private final GateRegisterService verdicts;
    private final ExceptionsRegisterService exceptions;
    private final RemediationDistributionService remediation;
    private final RuleCoverageService ruleCoverage;
    private final CertifiedScopeService scope;
    private final SettingsService settings;

    public ProcessEvidenceService(
            GateRegisterService verdicts,
            ExceptionsRegisterService exceptions,
            RemediationDistributionService remediation,
            RuleCoverageService ruleCoverage,
            CertifiedScopeService scope,
            SettingsService settings) {
        this.verdicts = verdicts;
        this.exceptions = exceptions;
        this.remediation = remediation;
        this.ruleCoverage = ruleCoverage;
        this.scope = scope;
        this.settings = settings;
    }

    /**
     * What the figures below do and do not account for.
     *
     * <p><b>Present in every section on purpose.</b> An archive is read by somebody who was not
     * there, cannot ask, and will otherwise assume the numbers mean what they would like them to
     * mean. Saying "read to a cap" or "narrowed to this reader's scope" costs a line and is the
     * difference between evidence and an assertion.
     *
     * @param scoped the generating account did not see the whole estate
     * @param truncated the read hit its cap, so the period starts at the oldest row read
     * @param note one sentence an assessor can quote
     */
    public record Coverage(boolean scoped, boolean truncated, String note) {}

    /**
     * @param month ISO {@code yyyy-MM}
     * @param refused how many of that month's verdicts were refusals
     */
    public record MonthlyActivity(String month, long total, long refused) {}

    /** One refusal, with the policy that produced it. */
    public record Refusal(
            String id,
            @JsonProperty("target_kind") String targetKind,
            @JsonProperty("target_id") Long targetId,
            int evaluated,
            int violations,
            @JsonProperty("counts_by_severity") Map<String, Long> countsBySeverity,
            @JsonProperty("fail_on_severity") String failOnSeverity,
            @JsonProperty("policy_source") String policySource,
            @JsonProperty("policy_version") Long policyVersion,
            @JsonProperty("relaxations_ignored") boolean relaxationsIgnored,
            @JsonProperty("decided_at") Instant decidedAt,
            @JsonProperty("requested_by") String requestedBy) {}

    /**
     * @param retentionDays the configured window, so a short period is read as a setting and not
     *     as a control that stopped running
     * @param monthly continuity — <b>read this before the totals</b>
     * @param refusalsListed how many of {@code refused} appear in {@code refusals}
     */
    public record GateEvidence(
            Coverage coverage,
            @JsonProperty("retention_days") int retentionDays,
            @JsonProperty("period_start") Instant periodStart,
            @JsonProperty("period_end") Instant periodEnd,
            long total,
            long passed,
            long refused,
            @JsonProperty("monthly_activity") List<MonthlyActivity> monthly,
            @JsonProperty("refusals_listed") int refusalsListed,
            List<Refusal> refusals) {}

    /**
     * Section 09 — that the barrier ran, and refused.
     *
     * @param allowed the generating account's allowance
     */
    @Transactional(readOnly = true)
    public GateEvidence gate(Visibility allowed) {
        List<GateVerdictView> read = verdicts.newest(VERDICT_READ_CAP);
        boolean truncated = read.size() >= VERDICT_READ_CAP;

        List<GateVerdictView> visible = read.stream()
                .filter(row -> allowed.permits(targetOf(row)))
                .toList();

        Map<String, long[]> byMonth = new TreeMap<>();
        for (GateVerdictView row : visible) {
            long[] tally = byMonth.computeIfAbsent(
                    YearMonth.from(row.decidedAt().atZone(ZoneOffset.UTC)).toString(),
                    key -> new long[2]);
            tally[0]++;
            if (!row.passed()) {
                tally[1]++;
            }
        }

        List<GateVerdictView> refusals =
                visible.stream().filter(row -> !row.passed()).toList();

        return new GateEvidence(
                new Coverage(
                        !(allowed instanceof Visibility.Everything),
                        truncated,
                        note(allowed, truncated) + retentionNote()),
                settings.asInt(Setting.EVIDENCE_RETENTION_DAYS),
                visible.stream().map(GateVerdictView::decidedAt).min(Comparator.naturalOrder()).orElse(null),
                visible.stream().map(GateVerdictView::decidedAt).max(Comparator.naturalOrder()).orElse(null),
                visible.size(),
                visible.size() - refusals.size(),
                refusals.size(),
                byMonth.entrySet().stream()
                        .map(e -> new MonthlyActivity(e.getKey(), e.getValue()[0], e.getValue()[1]))
                        .toList(),
                Math.min(refusals.size(), REFUSAL_LIST_CAP),
                refusals.stream().limit(REFUSAL_LIST_CAP).map(ProcessEvidenceService::refusal).toList());
    }

    /**
     * @param window the days the distribution covers
     */
    public record TimelinessEvidence(
            Coverage coverage,
            @JsonProperty("window_days") int windowDays,
            RemediationDistribution distribution) {}

    /** Section 11 — that deadlines are met, by the tail and not by the average. */
    @Transactional(readOnly = true)
    public TimelinessEvidence timeliness(Visibility allowed) {
        int window = RemediationDistributionService.MAX_WINDOW_DAYS;
        return new TimelinessEvidence(
                new Coverage(!(allowed instanceof Visibility.Everything), false, note(allowed, false)),
                window,
                remediation.distribution(window, allowed));
    }

    /**
     * @param freshnessDays what "recently scanned" meant when the frameworks above were evaluated
     */
    public record CoverageEvidence(
            @JsonProperty("freshness_days") int freshnessDays,
            @JsonProperty("rule_coverage") RuleCoverage.Assessment ruleCoverage,
            @JsonProperty("scope_statement") String scopeStatement,
            @JsonProperty("scope_coverage") ScopeCoverage scopeCoverage) {}

    /**
     * Section 12 — what the analysis was <em>able</em> to find.
     *
     * <p><b>The section that stops the rest of the bundle from lying.</b> An instance with no
     * Semgrep rules for the languages it holds reports zero code findings, and every framework
     * above it reads that as a clean result. Naming the gap is what turns "no findings" back into
     * "nothing was looked for".
     *
     * <p>Rule installation and the freshness setting are properties of the instance and are not
     * narrowed. The scope coverage beside them is: its denominator is the scope statement's own
     * asset count, which holds whoever is reading, and its numerator is the caller's slice — so a
     * restricted reader's figure is worse than the estate's, which is the honest arithmetic. A
     * reader who cannot see two thirds of the scope has not been told that two thirds of it is
     * fine.
     */
    @Transactional(readOnly = true)
    public CoverageEvidence coverage(Visibility allowed) {
        return new CoverageEvidence(
                Math.max(0, settings.asInt(Setting.COMPLIANCE_FRESHNESS_DAYS)),
                ruleCoverage.assess(),
                scope.statement(),
                scope.coverage(allowed));
    }

    /** Section 10 — what was argued away rather than fixed. */
    @Transactional(readOnly = true)
    public ExceptionsRegisterService.Register exceptions(Visibility allowed) {
        return exceptions.register(ExceptionsRegisterService.MAX_ENTRIES, null, allowed);
    }

    /**
     * Said in the archive, because it cannot be inferred from it.
     *
     * <p><b>A short period and a control that stopped running produce the same document.</b> An
     * instance keeping evidence for sixty days hands an assessor two months of verdicts and no way
     * to tell whether the other ten are missing or never happened. One sentence settles it — and
     * it is a sentence the operator would rather read before the assessment than during it.
     */
    private String retentionNote() {
        int days = settings.asInt(Setting.EVIDENCE_RETENTION_DAYS);
        if (days <= EvidenceRetention.UNLIMITED) {
            return " Evidence is kept indefinitely on this instance.";
        }
        if (days < 365) {
            return " Evidence is kept for " + days + " days on this instance, which is less than an annual "
                    + "assessment period: verdicts older than that were purged and are not missing from the "
                    + "record because the control lapsed.";
        }
        return "";
    }

    private static String note(Visibility allowed, boolean truncated) {
        StringBuilder note = new StringBuilder();
        note.append((allowed instanceof Visibility.Everything)
                ? "Covers the whole estate."
                : "Narrowed to the estate the generating account may see; this is not the whole estate.");
        if (truncated) {
            note.append(" The read reached its cap of ")
                    .append(VERDICT_READ_CAP)
                    .append(" verdicts, so the period below starts at the oldest row read and not at the "
                            + "start of retention.");
        }
        return note.toString();
    }

    private static ScanTarget targetOf(GateVerdictView row) {
        return row.repoId() != null
                ? new ScanTarget.Repository(row.repoId())
                : new ScanTarget.Container(row.containerId());
    }

    private static Refusal refusal(GateVerdictView row) {
        boolean isRepository = row.repoId() != null;
        return new Refusal(
                row.id().toString(),
                isRepository ? "REPOSITORY" : "CONTAINER",
                isRepository ? row.repoId() : row.containerId(),
                row.evaluated(),
                row.violations(),
                Map.of(
                        "critical", row.criticalCount(),
                        "high", row.highCount(),
                        "medium", row.mediumCount(),
                        "low", row.lowCount()),
                row.failOnSeverity(),
                row.policySource(),
                row.policyVersion(),
                row.relaxationsIgnored(),
                row.decidedAt(),
                row.decidedBy());
    }
}
