package com.asmolabs.vectispire.core.repositories;

import com.asmolabs.vectispire.core.persistence.ComplianceSnapshotEntity;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.transaction.annotation.Transactional;

/**
 * The monthly compliance captures.
 *
 * <p><b>No visibility clause, and here the reason is not the usual one.</b> A capture describes
 * the whole estate as the deployment saw it, which is what makes two months comparable; narrowing
 * it per reader would produce a different history for each of them and none of them an audit
 * trail. The route is gated on the role instead.
 */
public interface ComplianceSnapshots extends JpaRepository<ComplianceSnapshotEntity, UUID> {

    Optional<ComplianceSnapshotEntity> findByPeriodAndFramework(String period, String framework);

    /** Every capture, oldest first — the order a progression is read in. */
    @Query("select s from ComplianceSnapshotEntity s order by s.period asc, s.framework asc")
    List<ComplianceSnapshotEntity> findAllOrdered();

    /**
     * Drops captures older than the evidence window.
     *
     * <p>Under {@code evidence_retention_days} and not the payload window, for the reason spelt
     * out on {@code EvidenceRetention}: this is the record an assessment reads, not a blob that
     * can be regenerated by scanning again.
     */
    @Transactional
    @Modifying(clearAutomatically = true)
    @Query("delete from ComplianceSnapshotEntity s where s.capturedAt < :cutoff")
    int deleteBefore(@Param("cutoff") Instant cutoff);
}
