"""Messages already applied, so applying them twice is impossible.

The mirror image of `OutboxMessage`. Outbound delivery is at-least-once, and so
is inbound: an agent that posts a result and loses the response has no way to
know whether it arrived, so the only safe thing it can do is post it again.

Without a record of what has been applied, that retry is not harmless. The
obvious damage — 421 duplicated findings — is actually the part that was already
prevented: `Issue.fingerprint` makes reconciliation idempotent. The damage that
*would* have gone through is subtler and worse: `IssueService.sync_from_scan`
increments `times_seen` on every call, so a replayed report inflates the history
of every issue it mentions without creating a single visible duplicate. "Seen in
7 scans" would be a lie, and it is exactly the number an analyst uses to judge
whether a problem is chronic.

So the effect and the record of having applied it are written in the **same
transaction**. Either the results are in and this row exists, or neither does —
there is no ordering of a crash that produces one without the other.

Rows are pruned by retention alongside the delivered outbox messages: a message
id is only useful for as long as a sender might still retry it.
"""
from sqlalchemy import Column, Integer, String

from zanshin.clock import utcnow
from zanshin.database import Base
from zanshin.models.guid import GUID
from zanshin.models.safedatetime import SafeDateTime


class ProcessedMessage(Base):
    __tablename__ = "processed_message"

    id = Column(Integer, primary_key=True, index=True)

    # The sender's own identifier for this message, unique across senders — a
    # uuid, generated by the agent. Unique constraint rather than a "check then
    # insert": two retries arriving at once would both pass the check, and the
    # database is the only place that can arbitrate.
    message_id = Column(String(64), nullable=False, unique=True, index=True)

    # What kind of message, and which agent sent it. Neither is needed to
    # deduplicate; both are needed to answer "why does this scan hold results
    # from a machine that was decommissioned last month".
    message_type = Column(String(50), nullable=False)
    agent_id = Column(GUID, nullable=True)

    processed_at = Column(SafeDateTime, default=utcnow, nullable=False)
