apiVersion: v1
kind: Service
metadata:
  name: {{ include "vectispire.fullname" . }}
  labels:
    {{- include "vectispire.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vectispire.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
